/***************************************************************************************************
// -- Generated by AlteraxGen 17/02/2010 22:12:12
// Version 1.0
***************************************************************************************************/

using System;

namespace ScheduMail.Core.Domain
{
    /// <summary>
    /// Log Type (definition of log types for audititing purposes.
    /// </summary>
    [Serializable]
    public class LogType
    {
        /// <summary>
        /// The type id.
        /// </summary>
        private int typeId;

        /// <summary>
        /// Description for log
        /// </summary>
        private string description;

        /// <summary>
        /// Gets or sets the type id.
        /// </summary>
        /// <value>The type id.</value>
        public int TypeId
        {
            get
            {
                return this.typeId;
            }

            set
            {
                this.typeId = value;
            }
        }

        /// <summary>
        /// Gets or sets the description.
        /// </summary>
        /// <value>The description.</value>
        public string Description
        {
            get
            {
                return this.description;
            }

            set
            {
                this.description = value;
            }
        }
    }
}
