/***************************************************************************************************
// -- Generated by AlteraxGen 22/02/2010 20:48:54
// Version 1.0
***************************************************************************************************/

using System;

namespace ScheduMail.Core.Domain
{
    /// <summary>
    /// Schedule for sending of EMails.
    /// </summary>
    [Serializable]
    public class Schedule : BaseEntity
    {
        /// <summary>
        /// Mail Identification.
        /// </summary>
        private int mailId;

        /// <summary>
        /// Check for whether ir not enabled.
        /// </summary>
        private bool enabled;

        /// <summary>
        /// Start of Schedule.
        /// </summary>
        private DateTime startDateTime;

        /// <summary>
        /// Expiry of Schedule.
        /// </summary>
        private DateTime endDateTime;

        /// <summary>
        /// Days of Week to run.
        /// </summary>
        private int daysOfWeekToRun;

        /// <summary>
        /// Flag to indicate whether or not should be ran daily, weekly or monthly.
        /// </summary>
        private int dailyWeeklyOrMonthly;     

        /// <summary>
        /// Gets or sets the mail id.
        /// </summary>
        /// <value>The mail id.</value>
        public int MailId
        {
            get
            {
                return this.mailId;
            }

            set
            {
                this.mailId = value;
            }
        }

        /// <summary>
        /// Gets or sets the daily weekly or monthly.
        /// </summary>
        /// <value>The daily weekly or monthly.</value>
        public int DailyWeeklyOrMonthly
        {
            get 
            { 
                return dailyWeeklyOrMonthly; 
            }

            set 
            { 
                dailyWeeklyOrMonthly = value; 
            }
        }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="Schedule"/> is enabled.
        /// </summary>
        /// <value><c>true</c> if enabled; otherwise, <c>false</c>.</value>
        public bool Enabled
        {
            get
            {
                return this.enabled;
            }

            set
            {
                this.enabled = value;
            }
        }

        /// <summary>
        /// Gets or sets the start date time.
        /// </summary>
        /// <value>The start date time.</value>
        public DateTime StartDateTime
        {
            get
            {
                return this.startDateTime;
            }

            set
            {
                this.startDateTime = value;
            }
        }

        /// <summary>
        /// Gets or sets the end date time.
        /// </summary>
        /// <value>The end date time.</value>
        public DateTime EndDateTime
        {
            get
            {
                return this.endDateTime;
            }

            set
            {
                this.endDateTime = value;
            }
        }

        /// <summary>
        /// Gets or sets the days of week to run.
        /// </summary>
        /// <value>The days of week to run.</value>
        public int DaysOfWeekToRun
        {
            get
            {
                return this.daysOfWeekToRun;
            }

            set
            {
                this.daysOfWeekToRun = value;
            }
        }
    }
}
