/***************************************************************************************************
// -- Generated by AlteraxGen 17/02/2010 22:12:12
// Version 1.0
***************************************************************************************************/

using System;

namespace ScheduMail.Core.Domain
{
    /// <summary>
    /// Class to associate many to many relationship between User and Web Site
    /// </summary>
    [Serializable]
    public class UserWebSite
    {
        /// <summary>
        /// User ID
        /// </summary>
        private int userID;

        /// <summary>
        /// Web site ID
        /// </summary>
        private int webSiteID;

        /// <summary>
        /// Gets or sets the user ID.
        /// </summary>
        /// <value>The user ID.</value>
        public int UserID
        {
            get
            {
                return this.userID;
            }
            set
            {
                this.userID = value;
            }
        }

        /// <summary>
        /// Gets or sets the web site ID.
        /// </summary>
        /// <value>The web site ID.</value>
        public int WebSiteID
        {
            get
            {
                return this.webSiteID;
            }
            set
            {
                this.webSiteID = value;
            }
        }
    }
}
