//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SchedumailDBModel", "FK_LogEvent_0", "WebSite", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ScheduMail.DBModel.WebSite), "LogEvent", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ScheduMail.DBModel.LogEvent))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SchedumailDBModel", "FK_Mail_0", "WebSite", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ScheduMail.DBModel.WebSite), "Mail", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ScheduMail.DBModel.Mail))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SchedumailDBModel", "UserWebSite", "WebSite", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ScheduMail.DBModel.WebSite), "aspnet_Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ScheduMail.DBModel.aspnet_Users))]

// Original file name:
// Generation date: 18/02/2010 11:46:30
namespace ScheduMail.DBModel
{
    
    /// <summary>
    /// There are no comments for ScheduMailDBEntities in the schema.
    /// </summary>
    public partial class ScheduMailDBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new ScheduMailDBEntities object using the connection string found in the 'ScheduMailDBEntities' section of the application configuration file.
        /// </summary>
        public ScheduMailDBEntities() : 
                base("name=ScheduMailDBEntities", "ScheduMailDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ScheduMailDBEntities object.
        /// </summary>
        public ScheduMailDBEntities(string connectionString) : 
                base(connectionString, "ScheduMailDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ScheduMailDBEntities object.
        /// </summary>
        public ScheduMailDBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ScheduMailDBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for LogType in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<LogType> LogType
        {
            get
            {
                if ((this._LogType == null))
                {
                    this._LogType = base.CreateQuery<LogType>("[LogType]");
                }
                return this._LogType;
            }
        }
        private global::System.Data.Objects.ObjectQuery<LogType> _LogType;
        /// <summary>
        /// There are no comments for WebSite in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<WebSite> WebSite
        {
            get
            {
                if ((this._WebSite == null))
                {
                    this._WebSite = base.CreateQuery<WebSite>("[WebSite]");
                }
                return this._WebSite;
            }
        }
        private global::System.Data.Objects.ObjectQuery<WebSite> _WebSite;
        /// <summary>
        /// There are no comments for LogEvent in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<LogEvent> LogEvent
        {
            get
            {
                if ((this._LogEvent == null))
                {
                    this._LogEvent = base.CreateQuery<LogEvent>("[LogEvent]");
                }
                return this._LogEvent;
            }
        }
        private global::System.Data.Objects.ObjectQuery<LogEvent> _LogEvent;
        /// <summary>
        /// There are no comments for Mail in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Mail> Mail
        {
            get
            {
                if ((this._Mail == null))
                {
                    this._Mail = base.CreateQuery<Mail>("[Mail]");
                }
                return this._Mail;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Mail> _Mail;
        /// <summary>
        /// There are no comments for aspnet_Users in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<aspnet_Users> aspnet_Users
        {
            get
            {
                if ((this._aspnet_Users == null))
                {
                    this._aspnet_Users = base.CreateQuery<aspnet_Users>("[aspnet_Users]");
                }
                return this._aspnet_Users;
            }
        }
        private global::System.Data.Objects.ObjectQuery<aspnet_Users> _aspnet_Users;
        /// <summary>
        /// There are no comments for LogType in the schema.
        /// </summary>
        public void AddToLogType(LogType logType)
        {
            base.AddObject("LogType", logType);
        }
        /// <summary>
        /// There are no comments for WebSite in the schema.
        /// </summary>
        public void AddToWebSite(WebSite webSite)
        {
            base.AddObject("WebSite", webSite);
        }
        /// <summary>
        /// There are no comments for LogEvent in the schema.
        /// </summary>
        public void AddToLogEvent(LogEvent logEvent)
        {
            base.AddObject("LogEvent", logEvent);
        }
        /// <summary>
        /// There are no comments for Mail in the schema.
        /// </summary>
        public void AddToMail(Mail mail)
        {
            base.AddObject("Mail", mail);
        }
        /// <summary>
        /// There are no comments for aspnet_Users in the schema.
        /// </summary>
        public void AddToaspnet_Users(aspnet_Users aspnet_Users)
        {
            base.AddObject("aspnet_Users", aspnet_Users);
        }
    }
    /// <summary>
    /// There are no comments for SchedumailDBModel.LogType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TypeId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SchedumailDBModel", Name="LogType")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LogType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LogType object.
        /// </summary>
        /// <param name="typeId">Initial value of TypeId.</param>
        public static LogType CreateLogType(long typeId)
        {
            LogType logType = new LogType();
            logType.TypeId = typeId;
            return logType;
        }
        /// <summary>
        /// There are no comments for Property TypeId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long TypeId
        {
            get
            {
                return this._TypeId;
            }
            set
            {
                this.OnTypeIdChanging(value);
                this.ReportPropertyChanging("TypeId");
                this._TypeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TypeId");
                this.OnTypeIdChanged();
            }
        }
        private long _TypeId;
        partial void OnTypeIdChanging(long value);
        partial void OnTypeIdChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
    }
    /// <summary>
    /// There are no comments for SchedumailDBModel.WebSite in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SchedumailDBModel", Name="WebSite")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class WebSite : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new WebSite object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static WebSite CreateWebSite(long id)
        {
            WebSite webSite = new WebSite();
            webSite.Id = id;
            return webSite;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property SiteName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteName
        {
            get
            {
                return this._SiteName;
            }
            set
            {
                this.OnSiteNameChanging(value);
                this.ReportPropertyChanging("SiteName");
                this._SiteName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SiteName");
                this.OnSiteNameChanged();
            }
        }
        private string _SiteName;
        partial void OnSiteNameChanging(string value);
        partial void OnSiteNameChanged();
        /// <summary>
        /// There are no comments for Property Template in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Template
        {
            get
            {
                return this._Template;
            }
            set
            {
                this.OnTemplateChanging(value);
                this.ReportPropertyChanging("Template");
                this._Template = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Template");
                this.OnTemplateChanged();
            }
        }
        private string _Template;
        partial void OnTemplateChanging(string value);
        partial void OnTemplateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this.ReportPropertyChanging("Created");
                this._Created = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Created");
                this.OnCreatedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                this.ReportPropertyChanging("Modified");
                this._Modified = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Modified");
                this.OnModifiedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for LogEvent in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchedumailDBModel", "FK_LogEvent_0", "LogEvent")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<LogEvent> LogEvent
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<LogEvent>("SchedumailDBModel.FK_LogEvent_0", "LogEvent");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<LogEvent>("SchedumailDBModel.FK_LogEvent_0", "LogEvent", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Mail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchedumailDBModel", "FK_Mail_0", "Mail")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Mail> Mail
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Mail>("SchedumailDBModel.FK_Mail_0", "Mail");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Mail>("SchedumailDBModel.FK_Mail_0", "Mail", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for aspnet_Users in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchedumailDBModel", "UserWebSite", "aspnet_Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<aspnet_Users> aspnet_Users
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<aspnet_Users>("SchedumailDBModel.UserWebSite", "aspnet_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<aspnet_Users>("SchedumailDBModel.UserWebSite", "aspnet_Users", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SchedumailDBModel.LogEvent in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SchedumailDBModel", Name="LogEvent")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LogEvent : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LogEvent object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static LogEvent CreateLogEvent(long id)
        {
            LogEvent logEvent = new LogEvent();
            logEvent.Id = id;
            return logEvent;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property LogEventTypeId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> LogEventTypeId
        {
            get
            {
                return this._LogEventTypeId;
            }
            set
            {
                this.OnLogEventTypeIdChanging(value);
                this.ReportPropertyChanging("LogEventTypeId");
                this._LogEventTypeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LogEventTypeId");
                this.OnLogEventTypeIdChanged();
            }
        }
        private global::System.Nullable<long> _LogEventTypeId;
        partial void OnLogEventTypeIdChanging(global::System.Nullable<long> value);
        partial void OnLogEventTypeIdChanged();
        /// <summary>
        /// There are no comments for Property Message in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this._Message;
            }
            set
            {
                this.OnMessageChanging(value);
                this.ReportPropertyChanging("Message");
                this._Message = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Message");
                this.OnMessageChanged();
            }
        }
        private string _Message;
        partial void OnMessageChanging(string value);
        partial void OnMessageChanged();
        /// <summary>
        /// There are no comments for Property SenderUserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderUserName
        {
            get
            {
                return this._SenderUserName;
            }
            set
            {
                this.OnSenderUserNameChanging(value);
                this.ReportPropertyChanging("SenderUserName");
                this._SenderUserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SenderUserName");
                this.OnSenderUserNameChanged();
            }
        }
        private string _SenderUserName;
        partial void OnSenderUserNameChanging(string value);
        partial void OnSenderUserNameChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this.ReportPropertyChanging("Created");
                this._Created = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Created");
                this.OnCreatedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                this.ReportPropertyChanging("Modified");
                this._Modified = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Modified");
                this.OnModifiedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for WebSite in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchedumailDBModel", "FK_LogEvent_0", "WebSite")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public WebSite WebSite
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<WebSite>("SchedumailDBModel.FK_LogEvent_0", "WebSite").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<WebSite>("SchedumailDBModel.FK_LogEvent_0", "WebSite").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for WebSite in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<WebSite> WebSiteReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<WebSite>("SchedumailDBModel.FK_LogEvent_0", "WebSite");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<WebSite>("SchedumailDBModel.FK_LogEvent_0", "WebSite", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SchedumailDBModel.Mail in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SchedumailDBModel", Name="Mail")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Mail : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Mail object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static Mail CreateMail(long id)
        {
            Mail mail = new Mail();
            mail.Id = id;
            return mail;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Subject in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this._Subject;
            }
            set
            {
                this.OnSubjectChanging(value);
                this.ReportPropertyChanging("Subject");
                this._Subject = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Subject");
                this.OnSubjectChanged();
            }
        }
        private string _Subject;
        partial void OnSubjectChanging(string value);
        partial void OnSubjectChanged();
        /// <summary>
        /// There are no comments for Property EMailContent in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EMailContent
        {
            get
            {
                return this._EMailContent;
            }
            set
            {
                this.OnEMailContentChanging(value);
                this.ReportPropertyChanging("EMailContent");
                this._EMailContent = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EMailContent");
                this.OnEMailContentChanged();
            }
        }
        private string _EMailContent;
        partial void OnEMailContentChanging(string value);
        partial void OnEMailContentChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this.ReportPropertyChanging("UserName");
                this._UserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UserName");
                this.OnUserNameChanged();
            }
        }
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this.ReportPropertyChanging("Created");
                this._Created = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Created");
                this.OnCreatedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                this.ReportPropertyChanging("Modified");
                this._Modified = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Modified");
                this.OnModifiedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for WebSite in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchedumailDBModel", "FK_Mail_0", "WebSite")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public WebSite WebSite
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<WebSite>("SchedumailDBModel.FK_Mail_0", "WebSite").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<WebSite>("SchedumailDBModel.FK_Mail_0", "WebSite").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for WebSite in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<WebSite> WebSiteReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<WebSite>("SchedumailDBModel.FK_Mail_0", "WebSite");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<WebSite>("SchedumailDBModel.FK_Mail_0", "WebSite", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SchedumailDBModel.aspnet_Users in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SchedumailDBModel", Name="aspnet_Users")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class aspnet_Users : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new aspnet_Users object.
        /// </summary>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="username">Initial value of Username.</param>
        /// <param name="loweredUsername">Initial value of LoweredUsername.</param>
        /// <param name="applicationId">Initial value of ApplicationId.</param>
        /// <param name="password">Initial value of Password.</param>
        /// <param name="passwordFormat">Initial value of PasswordFormat.</param>
        /// <param name="passwordSalt">Initial value of PasswordSalt.</param>
        /// <param name="isApproved">Initial value of IsApproved.</param>
        /// <param name="isAnonymous">Initial value of IsAnonymous.</param>
        /// <param name="lastActivityDate">Initial value of LastActivityDate.</param>
        /// <param name="lastLoginDate">Initial value of LastLoginDate.</param>
        /// <param name="lastPasswordChangedDate">Initial value of LastPasswordChangedDate.</param>
        /// <param name="createDate">Initial value of CreateDate.</param>
        /// <param name="isLockedOut">Initial value of IsLockedOut.</param>
        /// <param name="lastLockoutDate">Initial value of LastLockoutDate.</param>
        /// <param name="failedPasswordAttemptCount">Initial value of FailedPasswordAttemptCount.</param>
        /// <param name="failedPasswordAttemptWindowStart">Initial value of FailedPasswordAttemptWindowStart.</param>
        /// <param name="failedPasswordAnswerAttemptCount">Initial value of FailedPasswordAnswerAttemptCount.</param>
        /// <param name="failedPasswordAnswerAttemptWindowStart">Initial value of FailedPasswordAnswerAttemptWindowStart.</param>
        public static aspnet_Users Createaspnet_Users(
                    string userId, 
                    string username, 
                    string loweredUsername, 
                    string applicationId, 
                    string password, 
                    string passwordFormat, 
                    string passwordSalt, 
                    bool isApproved, 
                    bool isAnonymous, 
                    global::System.DateTime lastActivityDate, 
                    global::System.DateTime lastLoginDate, 
                    global::System.DateTime lastPasswordChangedDate, 
                    global::System.DateTime createDate, 
                    bool isLockedOut, 
                    global::System.DateTime lastLockoutDate, 
                    long failedPasswordAttemptCount, 
                    global::System.DateTime failedPasswordAttemptWindowStart, 
                    long failedPasswordAnswerAttemptCount, 
                    global::System.DateTime failedPasswordAnswerAttemptWindowStart)
        {
            aspnet_Users aspnet_Users = new aspnet_Users();
            aspnet_Users.UserId = userId;
            aspnet_Users.Username = username;
            aspnet_Users.LoweredUsername = loweredUsername;
            aspnet_Users.ApplicationId = applicationId;
            aspnet_Users.Password = password;
            aspnet_Users.PasswordFormat = passwordFormat;
            aspnet_Users.PasswordSalt = passwordSalt;
            aspnet_Users.IsApproved = isApproved;
            aspnet_Users.IsAnonymous = isAnonymous;
            aspnet_Users.LastActivityDate = lastActivityDate;
            aspnet_Users.LastLoginDate = lastLoginDate;
            aspnet_Users.LastPasswordChangedDate = lastPasswordChangedDate;
            aspnet_Users.CreateDate = createDate;
            aspnet_Users.IsLockedOut = isLockedOut;
            aspnet_Users.LastLockoutDate = lastLockoutDate;
            aspnet_Users.FailedPasswordAttemptCount = failedPasswordAttemptCount;
            aspnet_Users.FailedPasswordAttemptWindowStart = failedPasswordAttemptWindowStart;
            aspnet_Users.FailedPasswordAnswerAttemptCount = failedPasswordAnswerAttemptCount;
            aspnet_Users.FailedPasswordAnswerAttemptWindowStart = failedPasswordAnswerAttemptWindowStart;
            return aspnet_Users;
        }
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this.ReportPropertyChanging("UserId");
                this._UserId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UserId");
                this.OnUserIdChanged();
            }
        }
        private string _UserId;
        partial void OnUserIdChanging(string value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property Username in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this._Username;
            }
            set
            {
                this.OnUsernameChanging(value);
                this.ReportPropertyChanging("Username");
                this._Username = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Username");
                this.OnUsernameChanged();
            }
        }
        private string _Username;
        partial void OnUsernameChanging(string value);
        partial void OnUsernameChanged();
        /// <summary>
        /// There are no comments for Property LoweredUsername in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LoweredUsername
        {
            get
            {
                return this._LoweredUsername;
            }
            set
            {
                this.OnLoweredUsernameChanging(value);
                this.ReportPropertyChanging("LoweredUsername");
                this._LoweredUsername = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LoweredUsername");
                this.OnLoweredUsernameChanged();
            }
        }
        private string _LoweredUsername;
        partial void OnLoweredUsernameChanging(string value);
        partial void OnLoweredUsernameChanged();
        /// <summary>
        /// There are no comments for Property ApplicationId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationId
        {
            get
            {
                return this._ApplicationId;
            }
            set
            {
                this.OnApplicationIdChanging(value);
                this.ReportPropertyChanging("ApplicationId");
                this._ApplicationId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ApplicationId");
                this.OnApplicationIdChanged();
            }
        }
        private string _ApplicationId;
        partial void OnApplicationIdChanging(string value);
        partial void OnApplicationIdChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property LoweredEmail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LoweredEmail
        {
            get
            {
                return this._LoweredEmail;
            }
            set
            {
                this.OnLoweredEmailChanging(value);
                this.ReportPropertyChanging("LoweredEmail");
                this._LoweredEmail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("LoweredEmail");
                this.OnLoweredEmailChanged();
            }
        }
        private string _LoweredEmail;
        partial void OnLoweredEmailChanging(string value);
        partial void OnLoweredEmailChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this.ReportPropertyChanging("Comment");
                this._Comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Comment");
                this.OnCommentChanged();
            }
        }
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property PasswordFormat in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordFormat
        {
            get
            {
                return this._PasswordFormat;
            }
            set
            {
                this.OnPasswordFormatChanging(value);
                this.ReportPropertyChanging("PasswordFormat");
                this._PasswordFormat = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PasswordFormat");
                this.OnPasswordFormatChanged();
            }
        }
        private string _PasswordFormat;
        partial void OnPasswordFormatChanging(string value);
        partial void OnPasswordFormatChanged();
        /// <summary>
        /// There are no comments for Property PasswordSalt in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordSalt
        {
            get
            {
                return this._PasswordSalt;
            }
            set
            {
                this.OnPasswordSaltChanging(value);
                this.ReportPropertyChanging("PasswordSalt");
                this._PasswordSalt = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PasswordSalt");
                this.OnPasswordSaltChanged();
            }
        }
        private string _PasswordSalt;
        partial void OnPasswordSaltChanging(string value);
        partial void OnPasswordSaltChanged();
        /// <summary>
        /// There are no comments for Property PasswordQuestion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordQuestion
        {
            get
            {
                return this._PasswordQuestion;
            }
            set
            {
                this.OnPasswordQuestionChanging(value);
                this.ReportPropertyChanging("PasswordQuestion");
                this._PasswordQuestion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PasswordQuestion");
                this.OnPasswordQuestionChanged();
            }
        }
        private string _PasswordQuestion;
        partial void OnPasswordQuestionChanging(string value);
        partial void OnPasswordQuestionChanged();
        /// <summary>
        /// There are no comments for Property PasswordAnswer in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordAnswer
        {
            get
            {
                return this._PasswordAnswer;
            }
            set
            {
                this.OnPasswordAnswerChanging(value);
                this.ReportPropertyChanging("PasswordAnswer");
                this._PasswordAnswer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PasswordAnswer");
                this.OnPasswordAnswerChanged();
            }
        }
        private string _PasswordAnswer;
        partial void OnPasswordAnswerChanging(string value);
        partial void OnPasswordAnswerChanged();
        /// <summary>
        /// There are no comments for Property IsApproved in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApproved
        {
            get
            {
                return this._IsApproved;
            }
            set
            {
                this.OnIsApprovedChanging(value);
                this.ReportPropertyChanging("IsApproved");
                this._IsApproved = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsApproved");
                this.OnIsApprovedChanged();
            }
        }
        private bool _IsApproved;
        partial void OnIsApprovedChanging(bool value);
        partial void OnIsApprovedChanged();
        /// <summary>
        /// There are no comments for Property IsAnonymous in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAnonymous
        {
            get
            {
                return this._IsAnonymous;
            }
            set
            {
                this.OnIsAnonymousChanging(value);
                this.ReportPropertyChanging("IsAnonymous");
                this._IsAnonymous = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsAnonymous");
                this.OnIsAnonymousChanged();
            }
        }
        private bool _IsAnonymous;
        partial void OnIsAnonymousChanging(bool value);
        partial void OnIsAnonymousChanged();
        /// <summary>
        /// There are no comments for Property LastActivityDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastActivityDate
        {
            get
            {
                return this._LastActivityDate;
            }
            set
            {
                this.OnLastActivityDateChanging(value);
                this.ReportPropertyChanging("LastActivityDate");
                this._LastActivityDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastActivityDate");
                this.OnLastActivityDateChanged();
            }
        }
        private global::System.DateTime _LastActivityDate;
        partial void OnLastActivityDateChanging(global::System.DateTime value);
        partial void OnLastActivityDateChanged();
        /// <summary>
        /// There are no comments for Property LastLoginDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastLoginDate
        {
            get
            {
                return this._LastLoginDate;
            }
            set
            {
                this.OnLastLoginDateChanging(value);
                this.ReportPropertyChanging("LastLoginDate");
                this._LastLoginDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastLoginDate");
                this.OnLastLoginDateChanged();
            }
        }
        private global::System.DateTime _LastLoginDate;
        partial void OnLastLoginDateChanging(global::System.DateTime value);
        partial void OnLastLoginDateChanged();
        /// <summary>
        /// There are no comments for Property LastPasswordChangedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastPasswordChangedDate
        {
            get
            {
                return this._LastPasswordChangedDate;
            }
            set
            {
                this.OnLastPasswordChangedDateChanging(value);
                this.ReportPropertyChanging("LastPasswordChangedDate");
                this._LastPasswordChangedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastPasswordChangedDate");
                this.OnLastPasswordChangedDateChanged();
            }
        }
        private global::System.DateTime _LastPasswordChangedDate;
        partial void OnLastPasswordChangedDateChanging(global::System.DateTime value);
        partial void OnLastPasswordChangedDateChanged();
        /// <summary>
        /// There are no comments for Property CreateDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this.ReportPropertyChanging("CreateDate");
                this._CreateDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreateDate");
                this.OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// There are no comments for Property IsLockedOut in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLockedOut
        {
            get
            {
                return this._IsLockedOut;
            }
            set
            {
                this.OnIsLockedOutChanging(value);
                this.ReportPropertyChanging("IsLockedOut");
                this._IsLockedOut = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsLockedOut");
                this.OnIsLockedOutChanged();
            }
        }
        private bool _IsLockedOut;
        partial void OnIsLockedOutChanging(bool value);
        partial void OnIsLockedOutChanged();
        /// <summary>
        /// There are no comments for Property LastLockoutDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastLockoutDate
        {
            get
            {
                return this._LastLockoutDate;
            }
            set
            {
                this.OnLastLockoutDateChanging(value);
                this.ReportPropertyChanging("LastLockoutDate");
                this._LastLockoutDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastLockoutDate");
                this.OnLastLockoutDateChanged();
            }
        }
        private global::System.DateTime _LastLockoutDate;
        partial void OnLastLockoutDateChanging(global::System.DateTime value);
        partial void OnLastLockoutDateChanged();
        /// <summary>
        /// There are no comments for Property FailedPasswordAttemptCount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long FailedPasswordAttemptCount
        {
            get
            {
                return this._FailedPasswordAttemptCount;
            }
            set
            {
                this.OnFailedPasswordAttemptCountChanging(value);
                this.ReportPropertyChanging("FailedPasswordAttemptCount");
                this._FailedPasswordAttemptCount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FailedPasswordAttemptCount");
                this.OnFailedPasswordAttemptCountChanged();
            }
        }
        private long _FailedPasswordAttemptCount;
        partial void OnFailedPasswordAttemptCountChanging(long value);
        partial void OnFailedPasswordAttemptCountChanged();
        /// <summary>
        /// There are no comments for Property FailedPasswordAttemptWindowStart in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime FailedPasswordAttemptWindowStart
        {
            get
            {
                return this._FailedPasswordAttemptWindowStart;
            }
            set
            {
                this.OnFailedPasswordAttemptWindowStartChanging(value);
                this.ReportPropertyChanging("FailedPasswordAttemptWindowStart");
                this._FailedPasswordAttemptWindowStart = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FailedPasswordAttemptWindowStart");
                this.OnFailedPasswordAttemptWindowStartChanged();
            }
        }
        private global::System.DateTime _FailedPasswordAttemptWindowStart;
        partial void OnFailedPasswordAttemptWindowStartChanging(global::System.DateTime value);
        partial void OnFailedPasswordAttemptWindowStartChanged();
        /// <summary>
        /// There are no comments for Property FailedPasswordAnswerAttemptCount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long FailedPasswordAnswerAttemptCount
        {
            get
            {
                return this._FailedPasswordAnswerAttemptCount;
            }
            set
            {
                this.OnFailedPasswordAnswerAttemptCountChanging(value);
                this.ReportPropertyChanging("FailedPasswordAnswerAttemptCount");
                this._FailedPasswordAnswerAttemptCount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FailedPasswordAnswerAttemptCount");
                this.OnFailedPasswordAnswerAttemptCountChanged();
            }
        }
        private long _FailedPasswordAnswerAttemptCount;
        partial void OnFailedPasswordAnswerAttemptCountChanging(long value);
        partial void OnFailedPasswordAnswerAttemptCountChanged();
        /// <summary>
        /// There are no comments for Property FailedPasswordAnswerAttemptWindowStart in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime FailedPasswordAnswerAttemptWindowStart
        {
            get
            {
                return this._FailedPasswordAnswerAttemptWindowStart;
            }
            set
            {
                this.OnFailedPasswordAnswerAttemptWindowStartChanging(value);
                this.ReportPropertyChanging("FailedPasswordAnswerAttemptWindowStart");
                this._FailedPasswordAnswerAttemptWindowStart = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FailedPasswordAnswerAttemptWindowStart");
                this.OnFailedPasswordAnswerAttemptWindowStartChanged();
            }
        }
        private global::System.DateTime _FailedPasswordAnswerAttemptWindowStart;
        partial void OnFailedPasswordAnswerAttemptWindowStartChanging(global::System.DateTime value);
        partial void OnFailedPasswordAnswerAttemptWindowStartChanged();
        /// <summary>
        /// There are no comments for WebSite in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchedumailDBModel", "UserWebSite", "WebSite")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<WebSite> WebSite
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<WebSite>("SchedumailDBModel.UserWebSite", "WebSite");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<WebSite>("SchedumailDBModel.UserWebSite", "WebSite", value);
                }
            }
        }
    }
}
