/***************************************************************************************************
// -- Generated by AlteraxGen 17/02/2010 22:12:12
// Version 1.0
***************************************************************************************************/

using System;

namespace ScheduMail.Core.Domain
{
    /// <summary>
    /// Provides primitive audit capability using defined Log Types.
    /// </summary>
   [Serializable]
   public class LogEvent : BaseEntity
   {
       /// <summary>
       /// Log Type Id
       /// </summary>
      private int	logEventTypeId;

      /// <summary>
      /// Log event message
      /// </summary>
      private string	message;

      /// <summary>
      /// Sender user name. (Creator of EMail template)
      /// </summary>
      private string	senderUserName;

      /// <summary>
      /// Gets or sets the log event type id.
      /// </summary>
      /// <value>The log event type id.</value>
      public int LogEventTypeId
      {
         get
         {
            return this.logEventTypeId;
         }
         set
         {
            this.logEventTypeId = value;
         }
      }

      /// <summary>
      /// Gets or sets the message.
      /// </summary>
      /// <value>The message.</value>
      public string Message
      {
         get
         {
            return this.message;
         }
         set
         {
            this.message = value;
         }
      }

      /// <summary>
      /// Gets or sets the name of the sender user.
      /// </summary>
      /// <value>The name of the sender user.</value>
      public string SenderUserName
      {
         get
         {
            return this.senderUserName;
         }
         set
         {
            this.senderUserName = value;
         }
      }     
   }
}

