/***************************************************************************************************
// -- Generated by AlteraxGen 17/02/2010 22:12:12
// Version 1.0
***************************************************************************************************/

using System;

namespace ScheduMail.Core.Domain
{
    [Serializable]
    public class Role : BaseEntity
    {
        private string name;
        private string description;
        private bool isSystem;

        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                this.name = value;
            }
        }

        public string Description
        {
            get
            {
                return this.description;
            }
            set
            {
                this.description = value;
            }
        }

        public bool IsSystem
        {
            get
            {
                return this.isSystem;
            }
            set
            {
                this.isSystem = value;
            }
        }
    }
}
