/***************************************************************************************************
// -- Generated by AlteraxGen 17/02/2010 22:12:12
// Version 1.0
***************************************************************************************************/

using System;

namespace ScheduMail.Core.Domain
{
    /// <summary>
    /// Class to associate many to many relationship between User and Web Site
    /// </summary>
    [Serializable]
    public class UserWebSite
    {
        /// <summary>
        /// User ID identification.
        /// </summary>
        public string UserId { get; set; }

        /// <summary>
        /// Gets or sets the web site id.
        /// </summary>
        /// <value>The web site id.</value>
        public long WebSiteId { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [user subscribed to web site].
        /// </summary>
        /// <value>
        /// 	<c>true</c> if [user subscribed to web site]; otherwise, <c>false</c>.
        /// </value>
        public bool UserSubscribedToWebSite { get; set; }

        /// <summary>
        /// Gets or sets the name of the web site.
        /// </summary>
        /// <value>The name of the web site.</value>
        public string SiteName { get; set; }
    }
}
